/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesScienceOfReflectionRouteImport } from './routes/resources.science-of-reflection'
import { Route as ResourcesEmotionalAwarenessPatternsRouteImport } from './routes/resources.emotional-awareness-patterns'
import { Route as ResourcesDistressDetectionRouteImport } from './routes/resources.distress-detection'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesScienceOfReflectionRoute =
  ResourcesScienceOfReflectionRouteImport.update({
    id: '/science-of-reflection',
    path: '/science-of-reflection',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesEmotionalAwarenessPatternsRoute =
  ResourcesEmotionalAwarenessPatternsRouteImport.update({
    id: '/emotional-awareness-patterns',
    path: '/emotional-awareness-patterns',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesDistressDetectionRoute =
  ResourcesDistressDetectionRouteImport.update({
    id: '/distress-detection',
    path: '/distress-detection',
    getParentRoute: () => ResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/resources/distress-detection': typeof ResourcesDistressDetectionRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/resources/distress-detection': typeof ResourcesDistressDetectionRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/resources/distress-detection': typeof ResourcesDistressDetectionRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/join'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/use-cases'
    | '/resources/distress-detection'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/join'
    | '/privacy'
    | '/terms'
    | '/use-cases'
    | '/resources/distress-detection'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/join'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/use-cases'
    | '/resources/distress-detection'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  JoinRoute: typeof JoinRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/science-of-reflection': {
      id: '/resources/science-of-reflection'
      path: '/science-of-reflection'
      fullPath: '/resources/science-of-reflection'
      preLoaderRoute: typeof ResourcesScienceOfReflectionRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/emotional-awareness-patterns': {
      id: '/resources/emotional-awareness-patterns'
      path: '/emotional-awareness-patterns'
      fullPath: '/resources/emotional-awareness-patterns'
      preLoaderRoute: typeof ResourcesEmotionalAwarenessPatternsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/distress-detection': {
      id: '/resources/distress-detection'
      path: '/distress-detection'
      fullPath: '/resources/distress-detection'
      preLoaderRoute: typeof ResourcesDistressDetectionRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesDistressDetectionRoute: typeof ResourcesDistressDetectionRoute
  ResourcesEmotionalAwarenessPatternsRoute: typeof ResourcesEmotionalAwarenessPatternsRoute
  ResourcesScienceOfReflectionRoute: typeof ResourcesScienceOfReflectionRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesDistressDetectionRoute: ResourcesDistressDetectionRoute,
  ResourcesEmotionalAwarenessPatternsRoute:
    ResourcesEmotionalAwarenessPatternsRoute,
  ResourcesScienceOfReflectionRoute: ResourcesScienceOfReflectionRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  JoinRoute: JoinRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
