/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesScienceOfReflectionRouteImport } from './routes/resources.science-of-reflection'
import { Route as ResourcesEmotionalAwarenessPatternsRouteImport } from './routes/resources.emotional-awareness-patterns'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesScienceOfReflectionRoute =
  ResourcesScienceOfReflectionRouteImport.update({
    id: '/science-of-reflection',
    path: '/science-of-reflection',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesEmotionalAwarenessPatternsRoute =
  ResourcesEmotionalAwarenessPatternsRouteImport.update({
    id: '/emotional-awareness-patterns',
    path: '/emotional-awareness-patterns',
    getParentRoute: () => ResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/terms': typeof TermsRoute
  '/resources/emotional-awareness-patterns': typeof ResourcesEmotionalAwarenessPatternsRoute
  '/resources/science-of-reflection': typeof ResourcesScienceOfReflectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/resources/emotional-awareness-patterns'
    | '/resources/science-of-reflection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/science-of-reflection': {
      id: '/resources/science-of-reflection'
      path: '/science-of-reflection'
      fullPath: '/resources/science-of-reflection'
      preLoaderRoute: typeof ResourcesScienceOfReflectionRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/emotional-awareness-patterns': {
      id: '/resources/emotional-awareness-patterns'
      path: '/emotional-awareness-patterns'
      fullPath: '/resources/emotional-awareness-patterns'
      preLoaderRoute: typeof ResourcesEmotionalAwarenessPatternsRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesEmotionalAwarenessPatternsRoute: typeof ResourcesEmotionalAwarenessPatternsRoute
  ResourcesScienceOfReflectionRoute: typeof ResourcesScienceOfReflectionRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesEmotionalAwarenessPatternsRoute:
    ResourcesEmotionalAwarenessPatternsRoute,
  ResourcesScienceOfReflectionRoute: ResourcesScienceOfReflectionRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
